== ri-collection-explicit-feedback-google-play-review image:https://img.shields.io/badge/License-EPL%202.0-blue.svg["EPL 2.0", link="https://www.eclipse.org/legal/epl-2.0/"]

This microservice was created as a result of the OpenReq project funded by the European Union Horizon 2020 Research and Innovation programme under grant agreement No 732463.

== Technical description
=== What does the microservice do
*This microservice is not maintained.*

The goal of this microservice is to collect data from the Google Play Store, the official store for Android apps. In particular, this service collects the user reviews of a given app and returns them as a list in JSON format.

=== Which technologies are used
- Go (-> https://github.com/golang/go)
- Gorilla Mux (-> https://github.com/gorilla/mux)

=== How to install it
Run the following commands to start the microservice:

. docker build -t ri-collection-explicit-feedback-google-play-review .

. docker run -p 9621:9621 ri-collection-explicit-feedback-google-play-review

=== How to use it (high-level description)
- link:http://217.172.12.199/registry/#/services/ri-collection-explicit-feedback-google-play-review[Rendered Documentation]

=== Notes for developers 
None.

=== Sources
None.

== How to contribute
See OpenReq project contribution link:https://github.com/OpenReqEU/OpenReq/blob/master/CONTRIBUTING.md[Guidlines]

== License
Free use of this software is granted under the terms of the EPL version 2 (EPL2.0).